(()=>{
const adminMenu=['Usuarios','Recargas Wallet','Inventario Tienda','Productos','NFTs','Estadísticas globales','Auditoría','Configuración general'];
const nftAssets=[
  {name:'NFT Lobo Capucha',img:'assets/NFT LOBO CAPUCHA.jpeg'},
  {name:'NFT Loba Capucha',img:'assets/NFT LOBA CAPUCHA.png'},
  {name:'NFT Lobo con Gafas',img:'assets/NFT LOBO CON GAFAS.png'},
  {name:'NFT Loba con Gafas',img:'assets/NFT LOBA CON GAFAS.png'}
];
function persist(){if(typeof save==='function')save();}
function notify(t){if(typeof toast==='function')toast(t);}
function uid(){return Math.random().toString(36).slice(2,9);}
function today(){return new Date().toISOString().slice(0,10);}
function currentUser(){return typeof user==='function'?user():S.users.find(u=>u.email===S.currentUser)||S.users[0];}
function ensureAdmin(){S.users=S.users||[];S.products=S.products||[];S.nfts=S.nfts||[];S.audit=S.audit||[];S.wallet=S.wallet||[];S.rechargeRequests=S.rechargeRequests||[];S.settings=S.settings||{moodReward:2,streakReward:10,challengeReward:200};if(!S.users.some(u=>u.role==='student'))S.users.unshift({id:uid(),name:'Luna Estudiante',email:'estudiante@colegio.edu.ec',password:'wolves123',role:'student',grade:'Séptimo EGB',coins:3000,xp:120});}
function log(action){S.audit.unshift({date:new Date().toLocaleString(),role:'admin',action});persist();}
function shellHeader(){return typeof shell==='function'?shell('Panel Administrador'):`<div class="toolbar"><div><h2>Panel Administrador</h2><small>${currentUser().name}</small></div></div>`;}
function money(n){return Number(n||0).toLocaleString('es-EC');}
function counts(){return{users:S.users.length,students:S.users.filter(u=>u.role==='student').length,products:S.products.length,stock:S.products.reduce((a,p)=>a+Number(p.stock||0),0),requests:S.rechargeRequests.filter(r=>r.status==='Pendiente').length,alerts:(S.alerts||[]).length,chain:(S.chain||[]).length,audit:S.audit.length};}
function metric(t,v,detail){return `<article class="admin-stat"><small>${t}</small><strong>${v}</strong><span>${detail}</span></article>`;}
function hero(){const c=counts();return `<section class="admin-hero"><article class="admin-hero-card"><span class="admin-kicker">Centro de control WOLVES</span><h2>Operación institucional clara y segura</h2><p>Administra usuarios, recargas, productos, NFTs, auditoría y parámetros del ecosistema desde una consola visual lista para demo.</p><div class="admin-actions"><button class="primary-btn" data-admin-jump="Recargas Wallet">Revisar recargas</button><button class="ghost-btn" data-admin-jump="Inventario Tienda">Controlar stock</button><button class="ghost-btn" data-admin-jump="Auditoría">Ver auditoría</button></div></article><article class="admin-hero-card admin-mascot"><img src="assets/MASCOTA BRAZOS CRUZADOS.png" alt="Mascota administrador Wolves"></article></section><section class="admin-metrics">${metric('Usuarios',c.users,'Cuentas demo')}${metric('Estudiantes',c.students,'Activos')}${metric('Stock tienda',c.stock,'Productos POP')}${metric('Recargas pendientes',c.requests,'Wallet')}</section>`;}
function usersView(){return `<section class="admin-grid-2"><article class="admin-card"><div class="admin-panel-head"><div><h3>Crear usuario</h3><p>Alta rápida de cuentas demo institucionales.</p></div></div><div class="admin-form"><label>Nombre<input id="adminUserName" placeholder="Nombre completo"></label><label>Correo<input id="adminUserEmail" placeholder="correo@wolves.com"></label><label>Rol<select id="adminUserRole"><option value="student">Estudiante</option><option value="dece">DECE</option><option value="admin">Administrador</option></select></label><label>Grado / área<input id="adminUserGrade" placeholder="Séptimo EGB"></label><button class="primary-btn full" id="adminCreateUser">Crear usuario</button></div></article><article class="admin-card"><div class="admin-panel-head"><div><h3>Usuarios registrados</h3><p>Edita o elimina usuarios simulados.</p></div><span class="admin-badge">${S.users.length} cuentas</span></div><div class="admin-list">${S.users.map(u=>`<article class="admin-row"><div><h4>${u.name}</h4><p>${u.email} · ${u.role} · ${u.grade||'Sin grado'}</p><span class="admin-badge ${u.role==='student'?'green':''}">${money(u.coins||0)} EC</span></div><div class="admin-actions"><button class="ghost-btn admin-edit-user" data-id="${u.id}">Editar</button><button class="admin-reject admin-delete-user" data-id="${u.id}">Eliminar</button></div></article>`).join('')}</div></article></section>`;}
function rechargesView(){const rows=S.rechargeRequests;return `<section class="admin-card"><div class="admin-panel-head"><div><h3>Recargas Wallet</h3><p>Aprueba solicitudes cuando el estudiante pague en dólares al administrador.</p></div><span class="admin-badge yellow">${rows.filter(r=>r.status==='Pendiente').length} pendientes</span></div><div class="admin-list">${rows.length?rows.map(r=>`<article class="admin-recharge-row ${String(r.status).toLowerCase()}"><div><strong>${r.id} · ${r.studentName||r.studentEmail}</strong><span>${r.studentEmail}</span><small>${r.date||''}</small></div><div><b>$${r.usd} USD</b><span>${money(r.coins)} EightCoins</span><small>${r.method||'Pago demo'} · ${r.reference||'Sin referencia'}</small></div><p>${r.note||'Solicitud de recarga institucional.'}</p><div class="admin-recharge-actions">${r.status==='Pendiente'?`<button class="admin-approve admin-approve-recharge" data-id="${r.id}">Aprobar</button><button class="admin-reject admin-reject-recharge" data-id="${r.id}">Rechazar</button>`:`<span class="admin-badge ${r.status==='Aprobada'?'green':'red'}">${r.status}</span>`}</div></article>`).join(''):'<div class="admin-empty">Aún no hay solicitudes. Desde Wallet el estudiante puede solicitar una recarga.</div>'}</div></section>`;}
function inventoryView(){return `<section class="admin-card"><div class="admin-panel-head"><div><h3>Inventario Tienda</h3><p>Control de stock y disponibilidad de material POP.</p></div><button class="primary-btn" id="adminRestockAll">Restock demo +5</button></div><div class="admin-product-grid">${S.products.map(productCard).join('')}</div></section>`;}
function productCard(p){return `<article class="admin-card admin-product-card"><img src="${p.image||'assets/LOGO.png'}" alt="${p.name}"><div class="admin-product-body"><h4>${p.name}</h4><p>${p.description||'Producto oficial Wolves'}</p><div class="admin-product-meta"><span>$${p.usd||0} USD</span><span>${money(p.coins)} EC</span><span>Stock ${p.stock}</span></div><div class="admin-stock-control"><input type="number" min="0" value="${p.stock}" data-stock-id="${p.id}"><button class="ghost-btn admin-save-stock" data-id="${p.id}">Guardar</button><button class="admin-reject admin-delete-product" data-id="${p.id}">Eliminar</button></div></div></article>`;}
function productsView(){return `<section class="admin-grid-2"><article class="admin-card"><h3>Crear producto</h3><div class="admin-form"><label>Nombre<input id="productName" placeholder="Producto Wolves"></label><label>Precio USD<input id="productUsd" type="number" min="0" value="8"></label><label>Precio EC<input id="productEc" type="number" min="0" value="800"></label><label>Stock<input id="productStock" type="number" min="0" value="10"></label><label class="full">Imagen / archivo assets<input id="productImage" placeholder="assets/MATERIAL POP TAZA.jpeg"></label><label class="full">Descripción<textarea id="productDesc">Producto oficial de la manada Wolves.</textarea></label><button class="primary-btn full" id="adminCreateProduct">Crear producto</button></div></article><article class="admin-card"><div class="admin-panel-head"><div><h3>Catálogo activo</h3><p>Productos disponibles en Tienda Wolves.</p></div></div><div class="admin-list">${S.products.map(p=>`<article class="admin-row"><div><h4>${p.name}</h4><p>$${p.usd} · ${money(p.coins)} EC · Stock ${p.stock}</p></div><span class="admin-badge green">Activo</span></article>`).join('')}</div></article></section>`;}
function nftsView(){const unlocked=(S.nfts||[]).filter(n=>n.unlocked).length;return `<section class="admin-card"><div class="admin-panel-head"><div><h3>Gestión de NFTs</h3><p>Colección educativa de accesorios desbloqueables.</p></div><div class="admin-actions"><button class="primary-btn" id="unlockAllNfts">Desbloquear todos</button><button class="ghost-btn" id="lockAllNfts">Bloquear todos</button></div></div><div class="admin-nft-grid">${nftAssets.map(n=>{const saved=(S.nfts||[]).find(x=>x.name===n.name)||{};return `<article class="admin-card admin-nft-card"><img src="${n.img}" alt="${n.name}"><h4>${n.name}</h4><span class="admin-badge ${saved.unlocked?'green':'yellow'}">${saved.unlocked?'Desbloqueado':'Bloqueado'}</span><button class="ghost-btn admin-toggle-nft" data-name="${n.name}">${saved.unlocked?'Bloquear':'Desbloquear'}</button></article>`;}).join('')}</div><p>${unlocked} NFTs desbloqueados en la demo.</p></section>`;}
function statsView(){const c=counts();const rows=[['Usuarios activos',Math.min(100,c.users*18)],['Inventario disponible',Math.min(100,c.stock)],['Recargas procesadas',Math.min(100,S.rechargeRequests.length*22)],['Alertas generadas',Math.min(100,c.alerts*18)],['Blockchain registrada',Math.min(100,c.chain*15)],['Auditoría',Math.min(100,c.audit*12)]];return `<section class="admin-card"><div class="admin-panel-head"><div><h3>Estadísticas globales</h3><p>Resumen de operación de la plataforma WOLVES.</p></div><button class="ghost-btn" id="adminExportStats">Exportar CSV</button></div><div class="admin-grid-3">${metric('Usuarios',c.users,'Total plataforma')}${metric('Productos',c.products,'Catálogo')}${metric('Movimientos',S.wallet.length,'Wallet')}</div><div class="admin-bars">${rows.map(r=>`<div class="admin-bar-row"><strong>${r[0]}</strong><div class="admin-bar-track"><span style="width:${r[1]}%"></span></div><span>${r[1]}%</span></div>`).join('')}</div></section>`;}
function auditView(){return `<section class="admin-card"><div class="admin-panel-head"><div><h3>Auditoría</h3><p>Registro de acciones y cambios realizados en la demo.</p></div><button class="ghost-btn" id="clearAudit">Limpiar auditoría demo</button></div><div class="audit-timeline">${S.audit.length?S.audit.map(a=>`<article class="audit-item"><span class="audit-dot"></span><div><strong>${a.action}</strong><p>${a.date} · ${a.role||'admin'}</p></div></article>`).join(''):'<div class="admin-empty">Sin acciones registradas.</div>'}</div></section>`;}
function settingsView(){return `<section class="admin-grid-2"><article class="admin-card"><h3>Parámetros generales</h3><div class="admin-form"><label>Mood Check EC<input id="setMood" type="number" value="${S.settings.moodReward||2}"></label><label>Racha semanal EC<input id="setStreak" type="number" value="${S.settings.streakReward||10}"></label><label>Biblioteca retos EC<input id="setChallenge" type="number" value="${S.settings.challengeReward||200}"></label><label>Estado de plataforma<select id="setStatus"><option>Activa</option><option>Modo demo</option><option>Mantenimiento</option></select></label><button class="primary-btn full" id="saveAdminSettings">Guardar configuración</button></div></article><article class="admin-card"><h3>Seguridad y privacidad</h3><p>Los datos sensibles de emociones no se registran en blockchain. Las acciones administrativas quedan en auditoría local de la demo.</p><div class="admin-actions"><button class="ghost-btn" id="resetDemoNotDestructive">Recalcular demo</button></div></article></section>`;}
function adminBody(){const views={'Usuarios':usersView,'Recargas Wallet':rechargesView,'Inventario Tienda':inventoryView,'Productos':productsView,'NFTs':nftsView,'Estadísticas globales':statsView,'Auditoría':auditView,'Configuración general':settingsView};return `<div class="admin-pro">${active==='Usuarios'?hero():''}${(views[active]||usersView)()}</div>`;}
function adminUpgrade(){ensureAdmin();if(!adminMenu.includes(active))active='Usuarios';e('adminView').innerHTML=shellHeader()+adminBody();bindAdmin();persist();}
function bindAdmin(){
  document.querySelectorAll('[data-admin-jump]').forEach(b=>b.onclick=()=>{active=b.dataset.adminJump;render();});
  const createUser=document.getElementById('adminCreateUser');if(createUser)createUser.onclick=()=>{if(!adminUserName.value||!adminUserEmail.value)return notify('Completa nombre y correo');S.users.push({id:uid(),name:adminUserName.value,email:adminUserEmail.value,password:'wolves123',role:adminUserRole.value,grade:adminUserGrade.value||'Demo',coins:20,usd:0,xp:0});log('Usuario creado: '+adminUserEmail.value);notify('Usuario creado');render();};
  document.querySelectorAll('.admin-delete-user').forEach(b=>b.onclick=()=>{const u=S.users.find(x=>x.id===b.dataset.id);if(!u)return;S.users=S.users.filter(x=>x.id!==b.dataset.id);log('Usuario eliminado: '+u.email);notify('Usuario eliminado');render();});
  document.querySelectorAll('.admin-edit-user').forEach(b=>b.onclick=()=>{const u=S.users.find(x=>x.id===b.dataset.id);if(!u)return;const next=prompt('Nuevo nombre para '+u.email,u.name);if(next){u.name=next;log('Usuario editado: '+u.email);notify('Usuario editado');render();}});
  document.querySelectorAll('.admin-approve-recharge').forEach(b=>b.onclick=()=>approveRecharge(b.dataset.id));
  document.querySelectorAll('.admin-reject-recharge').forEach(b=>b.onclick=()=>rejectRecharge(b.dataset.id));
  document.querySelectorAll('.admin-save-stock').forEach(b=>b.onclick=()=>{const p=S.products.find(x=>x.id===b.dataset.id);const input=document.querySelector(`[data-stock-id="${b.dataset.id}"]`);if(p&&input){p.stock=Number(input.value||0);log('Stock actualizado: '+p.name+' = '+p.stock);notify('Stock actualizado');render();}});
  document.querySelectorAll('.admin-delete-product').forEach(b=>b.onclick=()=>{const p=S.products.find(x=>x.id===b.dataset.id);S.products=S.products.filter(x=>x.id!==b.dataset.id);log('Producto eliminado: '+(p?.name||b.dataset.id));notify('Producto eliminado');render();});
  const restock=document.getElementById('adminRestockAll');if(restock)restock.onclick=()=>{S.products.forEach(p=>p.stock=Number(p.stock||0)+5);log('Restock demo +5 en todo el inventario');notify('Restock aplicado');render();};
  const createProduct=document.getElementById('adminCreateProduct');if(createProduct)createProduct.onclick=()=>{if(!productName.value)return notify('Escribe nombre del producto');S.products.push({id:uid(),name:productName.value,usd:Number(productUsd.value||0),coins:Number(productEc.value||0),stock:Number(productStock.value||0),image:productImage.value||'assets/LOGO.png',description:productDesc.value});log('Producto creado: '+productName.value);notify('Producto creado');render();};
  document.querySelectorAll('.admin-toggle-nft').forEach(b=>b.onclick=()=>{let n=S.nfts.find(x=>x.name===b.dataset.name);if(!n){n={name:b.dataset.name,unlocked:false};S.nfts.push(n);}n.unlocked=!n.unlocked;log('NFT '+(n.unlocked?'desbloqueado: ':'bloqueado: ')+n.name);notify('NFT actualizado');render();});
  const unlock=document.getElementById('unlockAllNfts');if(unlock)unlock.onclick=()=>{nftAssets.forEach(a=>{let n=S.nfts.find(x=>x.name===a.name);if(!n){n={name:a.name};S.nfts.push(n);}n.unlocked=true;});log('Todos los NFTs desbloqueados');notify('NFTs desbloqueados');render();};
  const lock=document.getElementById('lockAllNfts');if(lock)lock.onclick=()=>{S.nfts.forEach(n=>n.unlocked=false);log('Todos los NFTs bloqueados');notify('NFTs bloqueados');render();};
  const saveSettings=document.getElementById('saveAdminSettings');if(saveSettings)saveSettings.onclick=()=>{S.settings.moodReward=Number(setMood.value||2);S.settings.streakReward=Number(setStreak.value||10);S.settings.challengeReward=Number(setChallenge.value||200);S.settings.status=setStatus.value;log('Configuración general guardada');notify('Configuración guardada');render();};
  const clear=document.getElementById('clearAudit');if(clear)clear.onclick=()=>{S.audit=[];notify('Auditoría demo limpiada');persist();render();};
  const exportStats=document.getElementById('adminExportStats');if(exportStats)exportCsv('admin-wolves-estadisticas.csv',[counts()]);
}
function approveRecharge(id){const r=S.rechargeRequests.find(x=>x.id===id);if(!r||r.status!=='Pendiente')return;const target=S.users.find(u=>u.email===r.studentEmail);if(!target)return notify('Estudiante no encontrado');target.coins=Number(target.coins||0)+Number(r.coins||0);target.eightCoins=target.coins;r.status='Aprobada';r.approvedBy=currentUser().name;r.approvedAt=new Date().toLocaleString();S.wallet.unshift({date:today(),type:'Recarga aprobada',amount:Number(r.coins||0),detail:`${r.studentName||r.studentEmail}: $${r.usd} USD`});log('Recarga aprobada: '+r.id);notify('Recarga aprobada');render();}
function rejectRecharge(id){const r=S.rechargeRequests.find(x=>x.id===id);if(!r||r.status!=='Pendiente')return;r.status='Rechazada';r.approvedBy=currentUser().name;r.approvedAt=new Date().toLocaleString();log('Recarga rechazada: '+r.id);notify('Recarga rechazada');render();}
function exportCsv(filename,rows){const keys=Object.keys(rows[0]||{demo:'sin datos'});const csv=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);notify('CSV exportado');}
window.addEventListener('load',()=>{if(typeof S==='undefined')return;menus.admin=adminMenu;window.admin=admin=adminUpgrade;if(S.role==='admin')render();});
})();