const KEY='wolves_mvp_v1';
const risk=['suicidio','morir','lastimarme','hacerme daño','nadie me quiere'];
const neg=['Triste','Ansioso','Enojado'];
const grades={'Básica Media':['Quinto EGB','Sexto EGB','Séptimo EGB'],'Básica Superior':['Octavo EGB','Noveno EGB','Décimo EGB'],'Bachillerato':['Primero BGU','Segundo BGU','Tercero BGU']};
const menus={guest:['Inicio','Problema','Solución','ODS','Cómo funciona','Equipo','Misión','Visión','Planes SaaS','Contacto'],student:['Perfil RPG','Mood Check','Wolf AI','Retos Mensuales','Wallet','Blockchain Explorer','Tienda Wolves','Comunidad Wolves'],dece:['Dashboard DECE','Semáforo Emocional','Mapa de bienestar','Gestión de alertas','Calendario de citas','Fichas de seguimiento','Estadísticas institucionales'],admin:['Usuarios','Inventario Tienda','Productos','NFTs','Estadísticas globales','Auditoría','Configuración general']};
let state=load(), active='', selected='Alegre';
function id(){return Math.random().toString(36).slice(2,10)}
function day(){return new Date().toISOString().slice(0,10)}
function base(){return{currentRole:'guest',currentUser:'estudiante@colegio.edu.ec',users:[{id:id(),name:'Luna Estudiante',email:'estudiante@colegio.edu.ec',password:'wolves123',role:'student',level:'Básica Media',grade:'Séptimo EGB',xp:120,coins:80,usd:0},{id:id(),name:'Equipo DECE',email:'dece@wolves.com',password:'wolves123',role:'dece',level:'Institucional',grade:'DECE',xp:0,coins:0,usd:0},{id:id(),name:'Admin Wolves',email:'admin@wolves.com',password:'wolves123',role:'admin',level:'Institucional',grade:'Administrador',xp:0,coins:0,usd:0}],moods:[],alerts:[],appointments:[],followups:[],wallet:[{date:day(),type:'Bienvenida',amount:80,detail:'Eight-Coins iniciales'}],chain:[],challenges:[],chat:[{from:'ai',text:'Hola, soy Wolf AI. Estoy aquí para acompañarte con calma y respeto.'}],community:[{id:id(),author:'Hazel',text:'Hoy la manada acompaña: respirar también es avanzar.',likes:8,xp:25},{id:id(),author:'Maite',text:'Pedir ayuda es una forma de valentía.',likes:12,xp:35}],products:['Hoodie Wolves|38|420|18','Gorra Wolves|18|180|25','Taza Wolves|12|120|32','Agenda Emocional|15|160|20','Llavero Wolves|6|60|45','Peluche Oficial Wolf|28|300|12'].map(x=>{let p=x.split('|');return{id:id(),name:p[0],usd:+p[1],coins:+p[2],stock:+p[3]}}),cart:[],nfts:['Corona Imperial','Gafas Alpha','Headset Cyber','Halo Zen'].map((n,i)=>({id:id(),name:n,unlocked:i==0})),audit:[],settings:{moodReward:2,streakReward:10,challengeReward:200}}}
function load(){return JSON.parse(localStorage.getItem(KEY)||'null')||base()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function user(){return state.users.find(u=>u.email==state.currentUser)||state.users[0]}
function toast(t){let n=document.getElementById('toast');n.textContent=t;n.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove('show'),3000)}
function audit(a){state.audit.unshift({date:new Date().toLocaleString(),role:state.currentRole,action:a});save()}
async function hash(t){let b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function block(a){let prev=state.chain[0]?.hash||'GENESIS-WOLVES',num=state.chain.length+1,h=await hash(num+a+prev);state.chain.unshift({number:num,date:new Date().toLocaleString(),action:a,hash:h,previous:prev});save()}
function reward(n,d){let u=user();u.coins+=n;state.wallet.unshift({date:day(),type:'Recompensa',amount:n,detail:d});toast('+'+n+' Eight-Coins: '+d);save()}
document.addEventListener('DOMContentLoaded',()=>{auth();demo();document.getElementById('menuToggle').onclick=()=>document.getElementById('sidebar').classList.toggle('open');render()});
function demo(){document.querySelectorAll('.demo-console button').forEach(b=>b.onclick=()=>role(b.dataset.role))}
function role(r){state.currentRole=r;if(r=='student')state.currentUser='estudiante@colegio.edu.ec';if(r=='dece')state.currentUser='dece@wolves.com';if(r=='admin')state.currentUser='admin@wolves.com';active='';audit('Cambio a rol '+r);save();render()}
function auth(){let m=document.getElementById('authModal');document.querySelectorAll('[data-open-auth]').forEach(b=>b.onclick=()=>openAuth(b.dataset.openAuth));document.getElementById('closeAuth').onclick=()=>m.close();document.getElementById('loginTab').onclick=()=>openAuth('login');document.getElementById('registerTab').onclick=()=>openAuth('register');let lv=document.getElementById('registerLevel');lv.innerHTML='';Object.keys(grades).forEach(g=>lv.add(new Option(g,g)));lv.onchange=fillGrades;fillGrades();document.getElementById('loginForm').onsubmit=e=>{e.preventDefault();let mail=loginEmail.value.trim(),pass=loginPassword.value,u=state.users.find(x=>x.email==mail&&x.password==pass);if(!u)return toast('Credenciales no encontradas. Usa wolves123.');state.currentUser=u.email;state.currentRole=u.role;m.close();audit('Inicio de sesión '+u.email);save();render()};document.getElementById('registerForm').onsubmit=e=>{e.preventDefault();let u={id:id(),name:registerName.value,email:registerEmail.value,password:registerPassword.value,level:registerLevel.value,grade:registerGrade.value,role:registerRole.value,xp:0,coins:20,usd:0};state.users.push(u);state.currentUser=u.email;state.currentRole=u.role;m.close();audit('Registro '+u.email);save();render()}}
function fillGrades(){registerGrade.innerHTML='';grades[registerLevel.value||'Básica Media'].forEach(g=>registerGrade.add(new Option(g,g)))}
function openAuth(mode){authModal.showModal();let l=mode=='login';loginTab.classList.toggle('active',l);registerTab.classList.toggle('active',!l);loginForm.classList.toggle('active',l);registerForm.classList.toggle('active',!l);authTitle.textContent=l?'Inicio de sesión institucional':'Registro institucional'}
function render(){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));let vid=state.currentRole=='guest'?'publicView':state.currentRole+'View';document.getElementById(vid).classList.add('active');menu();if(state.currentRole=='guest')publicView();if(state.currentRole=='student')studentView();if(state.currentRole=='dece')deceView();if(state.currentRole=='admin')adminView()}
function menu(){let items=menus[state.currentRole];if(!active)active=items[0];roleMenu.innerHTML=items.map(i=>`<button class='${i==active?'active':''}' data-menu='${i}'>${ico(i)} ${i}</button>`).join('');document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>{active=b.dataset.menu;sidebar.classList.remove('open');render()})}
function ico(t){if(t.includes('Mood'))return'🙂';if(t.includes('Wolf'))return'🤖';if(t.includes('Wallet'))return'🪙';if(t.includes('Tienda')||t.includes('Productos'))return'🛒';if(t.includes('DECE')||t.includes('alertas'))return'🚨';if(t.includes('NFT'))return'🔷';if(t.includes('Blockchain'))return'⛓';if(t.includes('Comunidad'))return'👥';if(t.includes('Configuración'))return'⚙';return'◆'}
function publicView(){publicView.innerHTML=`<section class='hero'><div class='hero-copy'><span class='eyebrow'>Plataforma inteligente de bienestar emocional</span><h1>WOLVES</h1><p>La tecnología detecta. La comunidad acompaña.</p><div class='metric-row'><button class='primary-btn' data-open-auth='login'>Iniciar sesión</button><button class='ghost-btn' data-open-auth='register'>Registrarse</button><span class='pill'>IA + Gamificación + Blockchain conceptual</span></div></div><div class='hero-card'><div class='wolf-avatar'>🐺</div><h3>Bienestar que protege la manada</h3><p>MVP para registrar emociones, acompañar estudiantes y activar alertas tempranas en Eight Academy.</p></div></section><section class='section-grid'>${card('Problema','Estudiantes viven estrés, ansiedad, tristeza o frustración sin una herramienta dinámica para detectar señales y acompañar a tiempo.')}${card('Solución','Mood Check, Wolf AI, retos, Eight-Coins, NFTs educativos y panel DECE para seguimiento preventivo.')}${card('ODS',`<div class='ods-row'><span class='pill green'>ODS 3 Salud y Bienestar</span><span class='pill'>ODS 4 Educación de Calidad</span><span class='pill yellow'>ODS 9 Innovación</span></div>`)}${card('Cómo funciona WOLVES','1. El estudiante registra su emoción. 2. Wolf AI orienta. 3. Si hay riesgo, se genera alerta. 4. El DECE acompaña. 5. La participación suma progreso.','wide')}${card('Equipo','Maite Bravo: líder. Hazel Yánez: marketing. David Palacios: diseño y programación. Anita Parreño: mentora.')}${card('Misión','Fortalecer la prevención, el acompañamiento y el seguimiento emocional estudiantil.')}${card('Visión','Ser una referencia educativa de innovación, bienestar emocional e inteligencia aplicada.')}${card('Planes SaaS',`<div class='section-grid'>${plan('Bronce','$499 anual','Mood Check y reportes básicos.')}${plan('Plata','$999 anual','Panel DECE, alertas y estadísticas.')}${plan('Oro','$2499 anual','Analítica, tienda, NFTs y configuración completa.')}</div>`,'full')}${card('Contacto','Eight Academy · Plataforma WOLVES · bienestar@wolves.edu.ec · Demo lista para Hackathon.','full')}</section>`;auth()}
function card(t,b,c=''){return`<article class='card ${c}'><h2>${t}</h2><p>${b}</p></article>`}function plan(a,b,c){return`<article class='module'><h3>${a}</h3><strong class='coin'>${b}</strong><p>${c}</p></article>`}
function head(t){let u=user();return`<div class='toolbar'><div><h2>${t}</h2><small>${u.name} · <span class='role-badge'>${u.grade}</span></small></div><span class='coin'>🪙 ${u.coins} Eight-Coins</span></div>`}
function studentView(){let v={'Perfil RPG':profile,'Mood Check':mood,'Wolf AI':ai,'Retos Mensuales':challenges,'Wallet':wallet,'Blockchain Explorer':chain,'Tienda Wolves':store,'Comunidad Wolves':community};studentView.innerHTML=head('Panel Estudiante')+v[active]();bindStudent()}
function profile(){let u=user();return`<section class='dashboard-grid'><article class='card'><div class='wolf-avatar'>🧑‍🎓</div><h3>${u.name}</h3><p>${u.grade} · ${u.level}</p><p>Frase motivacional: Cada registro es una señal de autocuidado.</p></article><article class='card'><h3>Progreso RPG</h3><p class='coin'>${u.coins} Eight-Coins</p><p>XP: ${u.xp}</p><div class='progress'><span style='width:${Math.min(u.xp,100)}%'></span></div></article><article class='card'><h3>NFTs</h3>${state.nfts.map(n=>`<span class='pill ${n.unlocked?'green':''}'>${n.unlocked?'🔓':'🔒'} ${n.name}</span>`).join('')}</article><article class='card full'><h3>Citas DECE</h3>${appointments()}</article></section>`}
function mood(){let days=['Lunes','Martes','Miércoles','Jueves','Viernes'],done=new Set(state.moods.map(x=>x.weekday));return`<section class='dashboard-grid'><article class='card wide'><h3>Registro emocional diario</h3><div class='emotion-grid'>${['Alegre','Tranquilo','Triste','Ansioso','Enojado'].map(e=>`<button class='choice emotion ${e==selected?'active':''}' data-e='${e}'><span class='emoji'>${em(e)}</span>${e}</button>`).join('')}</div><label>Intensidad 1 a 5<input id='moodIntensity' type='range' min='1' max='5' value='3'></label><label>Comentario opcional<textarea id='moodComment' placeholder='Escribe solo lo que te sientas cómodo compartiendo.'></textarea></label><button class='primary-btn' id='saveMood'>Registrar emoción</button></article><article class='card'><h3>Racha semanal</h3><div class='quick-row'>${days.map(d=>`<span class='pill ${done.has(d)?'green':''}'>${done.has(d)?'✓':'·'} ${d}</span>`).join('')}</div><p>+2 por registro diario. +10 por lunes a viernes.</p></article></section>`}
function ai(){return`<section class='dashboard-grid'><article class='card wide'><h3>Wolf AI</h3><div class='quick-row'>${['Estrés académico','Ansiedad escolar','Gratitud diaria','Técnicas de respiración','Conflictos con compañeros'].map(t=>`<button class='ghost-btn quick-ai' data-t='${t}'>${t}</button>`).join('')}</div><div class='chat-box'>${state.chat.map(m=>`<div class='message ${m.from}'>${m.text}</div>`).join('')}</div><label>Mensaje<input id='aiInput' placeholder='Cuéntame cómo te sientes hoy'></label><button class='primary-btn' id='sendAi'>Enviar</button></article><article class='card'><h3>Solicitar cita con DECE</h3><label>Motivo<textarea id='appointmentReason'></textarea></label><label>Fecha<input id='appointmentDate' type='date'></label><label>Hora<input id='appointmentTime' type='time'></label><button class='success-btn' id='requestAppointment'>Enviar solicitud</button></article></section>`}
function challenges(){let list=['Respiración 4-7-8','Anclaje mental 5-4-3-2-1','Reencuadre cognitivo','Relajación muscular progresiva','Compromiso de autocuidado'];return`<section class='card'><h3>Retos mensuales</h3><p>Completa los 5 retos para ganar +200 Eight-Coins y desbloquear NFTs.</p><div class='challenge-grid'>${list.map(x=>`<button class='choice challenge ${state.challenges.includes(x)?'active':''}' data-c='${x}'><span class='emoji'>🏆</span>${x}<br><small>${state.challenges.includes(x)?'Completado':'Pendiente'}</small></button>`).join('')}</div></section>`}
function wallet(){let u=user();return`<section class='dashboard-grid'><article class='card'><h3>Billetera digital</h3><p class='coin'>Eight-Coins: ${u.coins}</p><p>USD simulado: $${u.usd}</p><div class='quick-row'>${[5,10,20,50].map(v=>`<button class='ghost-btn recharge' data-usd='${v}'>Recargar $${v}</button>`).join('')}</div></article><article class='card wide'><h3>Historial</h3>${history()}</article></section>`}
function chain(){return`<section class='card'><h3>Blockchain Explorer conceptual</h3><p>Registra retos, logros, recompensas y canjes. No registra emociones ni datos sensibles.</p>${blocks()}</section>`}
function store(){return`<section class='dashboard-grid'><article class='card wide'><h3>Tienda Wolves</h3><div class='product-grid'>${state.products.map(p=>`<div class='module'><div class='emoji'>🎁</div><h3>${p.name}</h3><p>Stock: ${p.stock}</p><p>$${p.usd} · ${p.coins} Eight-Coins</p><button class='ghost-btn add-cart' data-id='${p.id}'>Agregar al carrito</button><button class='primary-btn redeem' data-id='${p.id}'>Canjear</button></div>`).join('')}</div></article><article class='card'><h3>Carrito</h3>${cart()}</article></section>`}
function community(){return`<section class='dashboard-grid'><article class='card wide'><h3>Muro de aliento</h3><label>Publicar mensaje<textarea id='communityText'></textarea></label><button class='primary-btn' id='publishPost'>Publicar</button><div class='list-box'>${state.community.map(p=>`<div class='message'><strong>${p.author}</strong><p>${p.text}</p><button class='ghost-btn like-post' data-id='${p.id}'>Me gusta · ${p.likes}</button></div>`).join('')}</div></article><article class='card'><h3>Ranking</h3>${[...state.community].sort((a,b)=>b.xp-a.xp).map(p=>`<p class='pill'>${p.author}: ${p.xp} XP · ${p.likes} likes</p>`).join('')}<h3>Logros</h3><p class='pill green'>Manada activa</p><p class='pill'>Aliado emocional</p></article></section>`}
function bindStudent(){document.querySelectorAll('.emotion').forEach(b=>b.onclick=()=>{selected=b.dataset.e;render()});if(saveMood)saveMood.onclick=saveMoodEntry;if(sendAi)sendAi.onclick=()=>sendAiMsg(aiInput.value);document.querySelectorAll('.quick-ai').forEach(b=>b.onclick=()=>sendAiMsg(b.dataset.t));if(requestAppointment)requestAppointment.onclick=reqAppointment;document.querySelectorAll('.challenge').forEach(b=>b.onclick=()=>finishChallenge(b.dataset.c));document.querySelectorAll('.recharge').forEach(b=>b.onclick=()=>{user().usd+=+b.dataset.usd;state.wallet.unshift({date:day(),type:'Recarga simulada',amount:'$'+b.dataset.usd,detail:'Saldo USD demo'});save();render()});document.querySelectorAll('.add-cart').forEach(b=>b.onclick=()=>{state.cart.push(b.dataset.id);toast('Producto agregado al carrito');save();render()});document.querySelectorAll('.redeem').forEach(b=>b.onclick=()=>redeem(b.dataset.id));if(publishPost)publishPost.onclick=post;document.querySelectorAll('.like-post').forEach(b=>b.onclick=()=>{let p=state.community.find(x=>x.id==b.dataset.id);p.likes++;p.xp+=2;save();render()})}
function saveMoodEntry(){let wd=new Date().toLocaleDateString('es-EC',{weekday:'long'}).replace(/^./,c=>c.toUpperCase()),e={id:id(),student:user().email,emotion:selected,intensity:+moodIntensity.value,comment:moodComment.value,date:day(),weekday:wd};state.moods.push(e);reward(state.settings.moodReward,'Mood Check diario');let recent=state.moods.filter(x=>x.student==e.student&&neg.includes(x.emotion)).slice(-3);if(recent.length>=3||(neg.includes(e.emotion)&&e.intensity>=4))alertAdd('Amarilla','Patrón emocional negativo detectado',e.student);let full=['Lunes','Martes','Miércoles','Jueves','Viernes'].every(d=>state.moods.some(x=>x.weekday==d));if(full&&!state.wallet.some(w=>w.detail=='Racha semanal completa'))reward(state.settings.streakReward,'Racha semanal completa');audit('Registro Mood Check');save();render()}
function sendAiMsg(t){if(!t.trim())return;state.chat.push({from:'user',text:t});let low=t.toLowerCase();if(risk.some(w=>low.includes(w))){state.chat.push({from:'ai',text:'Alerta de emergencia: no estás solo. Busca ahora a un adulto de confianza o al DECE. WOLVES activó una alerta roja.'});alertAdd('Roja','Palabra de riesgo detectada en Wolf AI',user().email);state.followups.unshift({id:id(),student:user().email,date:day(),observations:'Ficha automática por palabra de riesgo.',agreements:'Contacto prioritario con DECE.',file:'PDF simulado pendiente'})}else state.chat.push({from:'ai',text':response(t)});audit('Interacción Wolf AI');save();render()}
function response(t){if(t.includes('Respiración')||t.includes('Ansiedad'))return'Respira: inhala 4, sostén 7 y exhala 8. Repite tres veces.';if(t.includes('Estrés'))return'Divide la tarea en una acción pequeña de 10 minutos. Empezar también cuenta.';if(t.includes('Gratitud'))return'Escribe tres cosas pequeñas que sí estuvieron bien hoy.';if(t.includes('Conflictos'))return'Nombra lo que sientes y lo que necesitas antes de conversar.';return'Gracias por contarlo. Puedes registrar tu Mood Check, probar un reto o solicitar cita con DECE.'}
function alertAdd(level,reason,student){state.alerts.unshift({id:id(),level,reason,student,date:new Date().toLocaleString(),status:'Pendiente'});toast('Alerta '+level+' enviada al Panel DECE')}
function reqAppointment(){state.appointments.unshift({id:id(),student:user().email,reason:appointmentReason.value,date:appointmentDate.value,time:appointmentTime.value,status:'Solicitada'});toast('Solicitud enviada al DECE');audit('Solicitud cita DECE');save();render()}
async function finishChallenge(c){if(state.challenges.includes(c))return toast('Este reto ya está completado.');state.challenges.push(c);await block('Reto completado: '+c);if(state.challenges.length==5&&!state.wallet.some(w=>w.detail=='Cinco retos mensuales completados')){reward(state.settings.challengeReward,'Cinco retos mensuales completados');state.nfts.forEach(n=>n.unlocked=true);await block('NFTs educativos desbloqueados')}save();render()}
async function redeem(pid){let p=state.products.find(x=>x.id==pid),u=user();if(p.stock<=0)return toast('Producto sin stock.');if(u.coins<p.coins)return toast('Eight-Coins insuficientes.');u.coins-=p.coins;p.stock--;state.wallet.unshift({date:day(),type:'Canje',amount:-p.coins,detail:p.name});await block('Canje Tienda Wolves: '+p.name);toast('Canje realizado: '+p.name);save();render()}
function post(){if(!communityText.value.trim())return;state.community.unshift({id:id(),author:user().name,text:communityText.value,likes:0,xp:10});user().xp+=10;toast('+10 XP por fortalecer la comunidad');save();render()}
function deceView(){let v={'Dashboard DECE':deceDash,'Semáforo Emocional':traffic,'Mapa de bienestar':map,'Gestión de alertas':alerts,'Calendario de citas':deceCal,'Fichas de seguimiento':follow,'Estadísticas institucionales':stats};deceView.innerHTML=head('Panel DECE')+v[active]();bindDece()}
function deceDash(){return`<section class='dashboard-grid'>${metric('Alertas rojas',state.alerts.filter(a=>a.level=='Roja').length,'red')}${metric('Alertas amarillas',state.alerts.filter(a=>a.level=='Amarilla').length,'yellow')}${metric('Citas solicitadas',state.appointments.length,'green')}${card('Prioridad DECE','Revisar alertas rojas, agendar acompañamiento y guardar fichas de seguimiento.','full')}</section>`}
function traffic(){return`<section class='card'><h3>Semáforo emocional</h3><div class='section-grid'>${['Roja','Amarilla','Verde'].map(l=>`<article class='module'><h3>${l}</h3><p>${state.alerts.filter(a=>a.level==l).length} eventos registrados.</p></article>`).join('')}</div></section>`}
function map(){return`<section class='card'><h3>Mapa de bienestar</h3><div class='section-grid'>${Object.values(grades).flat().slice(0,6).map((g,i)=>`<article class='module'><h3>${g}</h3><div class='progress'><span style='width:${55+i*6}%'></span></div><p>Participación: ${55+i*6}%</p></article>`).join('')}</div></section>`}
function alerts(){return`<section class='card'><h3>Gestión de alertas</h3>${alertTable()}</section>`}
function deceCal(){return`<section class='card'><h3>Calendario de citas</h3>${appointments()}<button class='success-btn' id='confirmAppointments'>Marcar citas como agendadas</button></section>`}
function follow(){return`<section class='dashboard-grid'><article class='card'><h3>Registro de seguimiento</h3><label>Estudiante<input id='followStudent' value='estudiante@colegio.edu.ec'></label><label>Observaciones<textarea id='followObs'></textarea></label><label>Acuerdos<textarea id='followAgree'></textarea></label><label>Subida simulada PDF<input id='followFile' type='file' accept='application/pdf'></label><button class='primary-btn' id='saveFollow'>Guardar Seguimiento</button><button class='ghost-btn' id='exportCsv'>Exportar CSV</button></article><article class='card wide'><h3>Fichas</h3>${followList()}</article></section>`}
function stats(){let total=state.moods.length||1;return`<section class='dashboard-grid'>${metric('Participación estudiantil',state.moods.length+' registros','green')}${metric('Uso de Wolf AI',state.chat.length+' mensajes')}${metric('Retos completados',state.challenges.length,'yellow')}${metric('Alertas generadas',state.alerts.length,'red')}<article class='card full'><h3>Emociones predominantes</h3>${['Alegre','Tranquilo','Triste','Ansioso','Enojado'].map(e=>{let c=state.moods.filter(m=>m.emotion==e).length;return`<p>${e}</p><div class='progress'><span style='width:${c/total*100}%'></span></div>`}).join('')}</article></section>`}
function bindDece(){if(confirmAppointments)confirmAppointments.onclick=()=>{state.appointments.forEach(a=>a.status='Agendada');toast('Citas agendadas');save();render()};if(saveFollow)saveFollow.onclick=()=>{state.followups.unshift({id:id(),student:followStudent.value,date:day(),observations:followObs.value,agreements:followAgree.value,file:followFile.files[0]?.name||'PDF simulado'});toast('Ficha guardada');save();render()};if(exportCsv)exportCsv.onclick=csv}
function adminView(){let v={'Usuarios':users,'Inventario Tienda':inventory,'Productos':inventory,'NFTs':nfts,'Estadísticas globales':stats,'Auditoría':aud,'Configuración general':settings};adminView.innerHTML=head('Panel Administrador')+v[active]();bindAdmin()}
function users(){return`<section class='dashboard-grid'><article class='card'><h3>Crear usuario simulado</h3><label>Nombre<input id='newUserName'></label><label>Correo<input id='newUserEmail'></label><label>Rol<select id='newUserRole'><option value='student'>Estudiante</option><option value='dece'>DECE</option><option value='admin'>Administrador</option></select></label><button class='primary-btn' id='createUser'>Crear usuario</button></article><article class='card wide'><h3>Usuarios</h3>${usersTable()}</article></section>`}
function inventory(){return`<section class='card'><h3>Inventario Tienda</h3>${state.products.map(p=>`<div class='module'><h3>${p.name}</h3><p>$${p.usd} · ${p.coins} Eight-Coins</p><label>Stock<input class='stock-input' data-id='${p.id}' type='number' value='${p.stock}'></label></div>`).join('')}</section>`}
function nfts(){return`<section class='card'><h3>NFTs educativos</h3><div class='nft-grid'>${state.nfts.map(n=>`<span class='pill ${n.unlocked?'green':''}'>${n.name} · ${n.unlocked?'Desbloqueado':'Bloqueado'}</span>`).join('')}</div></section>`}
function aud(){return`<section class='card'><h3>Auditoría</h3>${state.audit.map(a=>`<p class='message'><strong>${a.date}</strong> · ${a.role}<br>${a.action}</p>`).join('')||'<p>No hay acciones.</p>'}</section>`}
function settings(){return`<section class='card'><h3>Configuración general</h3><label>Recompensa Mood<input id='setMood' type='number' value='${state.settings.moodReward}'></label><label>Recompensa racha<input id='setStreak' type='number' value='${state.settings.streakReward}'></label><label>Recompensa retos<input id='setChallenge' type='number' value='${state.settings.challengeReward}'></label><button class='primary-btn' id='saveSettings'>Guardar configuración</button></section>`}
function bindAdmin(){if(createUser)createUser.onclick=()=>{state.users.push({id:id(),name:newUserName.value||'Usuario WOLVES',email:newUserEmail.value||id()+'@colegio.edu.ec',password:'wolves123',role:newUserRole.value,level:'Básica Media',grade:'Séptimo EGB',xp:0,coins:20,usd:0});audit('Usuario creado');save();render()};document.querySelectorAll('.delete-user').forEach(b=>b.onclick=()=>{state.users=state.users.filter(u=>u.id!=b.dataset.id);audit('Usuario eliminado');save();render()});document.querySelectorAll('.edit-user').forEach(b=>b.onclick=()=>{let u=state.users.find(x=>x.id==b.dataset.id);u.name=prompt('Nuevo nombre',u.name)||u.name;audit('Usuario editado');save();render()});document.querySelectorAll('.stock-input').forEach(i=>i.onchange=()=>{state.products.find(p=>p.id==i.dataset.id).stock=+i.value;audit('Stock editado');save();toast('Stock actualizado')});if(saveSettings)saveSettings.onclick=()=>{state.settings.moodReward=+setMood.value;state.settings.streakReward=+setStreak.value;state.settings.challengeReward=+setChallenge.value;audit('Configuración actualizada');save();toast('Configuración guardada')}}
function em(e){return{Alegre:'😄',Tranquilo:'🙂',Triste:'😢',Ansioso:'😟',Enojado:'😡'}[e]}
function metric(l,v,c=''){return`<article class='card'><h3>${l}</h3><p class='pill ${c}'>${v}</p></article>`}
function history(){return`<table class='table'><tr><th>Fecha</th><th>Tipo</th><th>Monto</th><th>Detalle</th></tr>${state.wallet.map(h=>`<tr><td>${h.date}</td><td>${h.type}</td><td>${h.amount}</td><td>${h.detail}</td></tr>`).join('')}</table>`}
function blocks(){return`<table class='table'><tr><th>Bloque</th><th>Fecha</th><th>Acción</th><th>Hash</th><th>Anterior</th></tr>${state.chain.map(b=>`<tr><td>${b.number}</td><td>${b.date}</td><td>${b.action}</td><td>${b.hash.slice(0,18)}...</td><td>${b.previous.slice(0,12)}...</td></tr>`).join('')||'<tr><td colspan=5>Aún no hay bloques.</td></tr>'}</table>`}
function cart(){let items=state.cart.map(i=>state.products.find(p=>p.id==i)).filter(Boolean),usd=items.reduce((s,p)=>s+p.usd,0),coins=items.reduce((s,p)=>s+p.coins,0);return`${items.map(p=>`<p class='pill'>${p.name}</p>`).join('')||'<p>Carrito vacío.</p>'}<p>Total USD: $${usd}</p><p>Total Eight-Coins: ${coins}</p>`}
function appointments(){return state.appointments.map(a=>`<p class='message'><strong>${a.date||'Fecha por definir'} ${a.time||''}</strong><br>${a.student}<br>${a.reason||'Solicitud de acompañamiento'} · ${a.status}</p>`).join('')||'<p>No hay citas registradas.</p>'}
function alertTable(){return`<table class='table'><tr><th>Nivel</th><th>Estudiante</th><th>Motivo</th><th>Fecha</th><th>Estado</th></tr>${state.alerts.map(a=>`<tr><td class='${a.level=='Roja'?'red':a.level=='Amarilla'?'yellow':'green'}'>${a.level}</td><td>${a.student}</td><td>${a.reason}</td><td>${a.date}</td><td>${a.status}</td></tr>`).join('')||'<tr><td colspan=5>No hay alertas activas.</td></tr>'}</table>`}
function followList(){return state.followups.map(f=>`<div class='message'><strong>${f.student}</strong> · ${f.date}<p>Observaciones: ${f.observations}</p><p>Acuerdos: ${f.agreements}</p><p>Evidencia: ${f.file}</p></div>`).join('')||'<p>No hay fichas.</p>'}
function usersTable(){return`<table class='table'><tr><th>Nombre</th><th>Correo</th><th>Rol</th><th>Acciones</th></tr>${state.users.map(u=>`<tr><td>${u.name}</td><td>${u.email}</td><td>${u.role}</td><td><button class='ghost-btn edit-user' data-id='${u.id}'>Editar</button> <button class='danger-btn delete-user' data-id='${u.id}'>Eliminar</button></td></tr>`).join('')}</table>`}
function csv(){let rows=[['student','date','observations','agreements'],...state.followups.map(f=>[f.student,f.date,f.observations,f.agreements])],data=rows.map(r=>r.map(c=>'"'+String(c).replaceAll('"','""')+'"').join(',')).join('\n'),blob=new Blob([data],{type:'text/csv'}),url=URL.createObjectURL(blob),a=Object.assign(document.createElement('a'),{href:url,download:'wolves-seguimiento.csv'});a.click();URL.revokeObjectURL(url);toast('CSV exportado')}
