(()=>{
function currentUser(){return typeof user==='function'?user():S.users.find(u=>u.email===S.currentUser)||S.users[0];}
function persist(){if(typeof save==='function')save();}
function notify(text){if(typeof toast==='function')toast(text);}
function today(){return new Date().toISOString().slice(0,10);}
function ensureDeceData(){
  S.alerts=S.alerts||[];S.appointments=S.appointments||[];S.followups=S.followups||[];S.moods=S.moods||[];
  S.deceNotes=S.deceNotes||[];
  if(!S.deceSeeded){
    if(!S.alerts.length)S.alerts.push({level:'Amarilla',reason:'Ansiedad escolar recurrente',student:'estudiante@colegio.edu.ec',date:new Date().toLocaleString(),status:'Pendiente',source:'Mood Check'});
    if(!S.appointments.length)S.appointments.push({student:'estudiante@colegio.edu.ec',reason:'Conversar sobre carga academica',date:today(),time:'10:30',status:'Solicitada',createdAt:new Date().toLocaleString()});
    S.deceSeeded=true;persist();
  }
}
function shellHeader(){return typeof shell==='function'?shell('Panel DECE'):`<div class="toolbar"><div><h2>Panel DECE</h2><small>${currentUser().name}</small></div></div>`;}
function counts(){return{red:S.alerts.filter(a=>a.level==='Roja').length,yellow:S.alerts.filter(a=>a.level==='Amarilla').length,green:S.alerts.filter(a=>a.level==='Verde').length,appointments:S.appointments.length,followups:S.followups.length,moods:S.moods.length};}
function studentRows(){
  const students=S.users.filter(u=>u.role==='student');
  return students.length?students:[{name:'Luna Estudiante',email:'estudiante@colegio.edu.ec',grade:'Septimo EGB',coins:0,xp:0}];
}
function riskFor(email){
  const red=S.alerts.filter(a=>a.student===email&&a.level==='Roja').length;
  const yellow=S.alerts.filter(a=>a.student===email&&a.level==='Amarilla').length;
  const mood=S.moods.filter(m=>m.student===email).length;
  return Math.min(100,red*45+yellow*22+Math.max(0,25-mood));
}
function metric(title,value,type,detail){return `<article class="dece-stat ${type||'cyan'}"><small>${title}</small><strong>${value}</strong><span>${detail||'Monitoreo activo'}</span></article>`;}
function alertItem(a,i){const level=(a.level||'Verde').toLowerCase();return `<article class="dece-alert-row" data-alert-index="${i}"><span class="dece-dot ${level}"></span><div><h4>${a.level||'Verde'} · ${a.student||'Estudiante'}</h4><p>${a.reason||'Seguimiento preventivo'} · ${a.status||'Pendiente'}</p><p><small>${a.date||''} ${a.source?'· '+a.source:''}</small></p></div><div class="dece-actions"><button class="ghost-btn dece-attend" data-i="${i}">Atender</button><button class="primary-btn dece-to-follow" data-i="${i}">Crear ficha</button></div></article>`;}
function appointmentItem(a,i){return `<article class="dece-appointment"><span class="appointment-status">${a.status||'Solicitada'}</span><h4>${a.student}</h4><p>${a.reason||'Solicitud de acompanamiento'}</p><p><strong>${a.date||'Sin fecha'} · ${a.time||'Sin hora'}</strong></p><div class="dece-actions"><button class="primary-btn dece-schedule" data-i="${i}">Agendar</button><button class="ghost-btn dece-complete-appointment" data-i="${i}">Marcar realizada</button></div></article>`;}
function hero(){const c=counts();return `<section class="dece-hero"><article class="dece-hero-card"><span class="dece-kicker">Centro de acompanamiento DECE</span><h2>Bienestar escolar en tiempo real</h2><p>Visualiza alertas, agenda citas, registra seguimientos y toma decisiones con datos claros sin exponer informacion sensible.</p><div class="dece-actions"><button class="primary-btn" data-dece-jump="Gestión de alertas">Revisar alertas</button><button class="ghost-btn" data-dece-jump="Calendario de citas">Ver citas</button><button class="ghost-btn" data-dece-jump="Fichas de seguimiento">Nueva ficha</button></div></article><article class="dece-hero-card dece-mascot"><img src="assets/MASCOTA CORAZÓN.png" alt="Mascota Wolves DECE"></article></section><section class="dece-metrics">${metric('Alertas rojas',c.red,'red','Riesgo critico')}${metric('Alertas amarillas',c.yellow,'yellow','Atencion moderada')}${metric('Citas solicitadas',c.appointments,'green','Agenda DECE')}${metric('Fichas activas',c.followups,'cyan','Seguimientos')}${metric('Mood Checks',c.moods,'cyan','Participacion')}${metric('Estudiantes',studentRows().length,'green','Comunidad escolar')}</section>`;}
function dashboard(){return `${hero()}<section class="dece-split"><article class="dece-panel"><div class="dece-panel-head"><div><h3>Bandeja prioritaria</h3><p>Alertas ordenadas para accion inmediata.</p></div><button class="ghost-btn" data-dece-jump="Gestión de alertas">Abrir gestor</button></div><div class="dece-alert-list">${S.alerts.slice(0,5).map(alertItem).join('')||'<div class="dece-empty">No hay alertas pendientes.</div>'}</div></article><article class="dece-panel"><div class="dece-panel-head"><div><h3>Proximas citas</h3><p>Solicitudes y sesiones agendadas.</p></div></div><div class="dece-appointment-list">${S.appointments.slice(0,4).map(appointmentItem).join('')||'<div class="dece-empty">No hay citas solicitadas.</div>'}</div></article></section>`;}
function semaphore(){return `<section class="dece-panel"><div class="dece-panel-head"><div><h3>Semaforo emocional</h3><p>Clasificacion visual por nivel de riesgo institucional.</p></div><span class="dece-kicker">Rojo · Amarillo · Verde</span></div><div class="dece-grid-3">${studentRows().map(s=>{const r=riskFor(s.email);const tone=r>=65?'Roja':r>=32?'Amarilla':'Verde';return `<article class="dece-student"><div class="risk-ring" style="--risk:${r}%"><span>${r}%</span></div><h4>${s.name}</h4><p>${s.grade||'Curso demo'}</p><p><strong>${tone}</strong> · ${s.email}</p><button class="ghost-btn dece-student-follow" data-email="${s.email}">Registrar seguimiento</button></article>`;}).join('')}</div></section>`;}
function wellbeingMap(){const zones=['Quinto EGB','Sexto EGB','Septimo EGB','Octavo EGB','Noveno EGB','Decimo EGB','Bachillerato'];return `<section class="dece-panel"><div class="dece-panel-head"><div><h3>Mapa de bienestar</h3><p>Vista sintetica por cursos y niveles para priorizar acompanamiento.</p></div><button class="primary-btn" id="refreshMap">Actualizar lectura</button></div><div class="wellbeing-map">${zones.map((z,i)=>{const value=Math.max(45,88-(i*6)-counts().red*8-counts().yellow*3);return `<article class="grade-zone"><h4>${z}</h4><div class="zone-bar"><span style="width:${value}%"></span></div><div class="zone-meta"><span>${value}% bienestar</span><span>${value<60?'Prioridad':'Estable'}</span></div></article>`;}).join('')}</div></section>`;}
function alertsView(){return `<section class="dece-panel"><div class="dece-panel-head"><div><h3>Gestion de alertas</h3><p>Filtra, atiende y convierte alertas en fichas de seguimiento.</p></div><div class="dece-filter"><button class="ghost-btn dece-filter-btn" data-filter="Todas">Todas</button><button class="ghost-btn dece-filter-btn" data-filter="Roja">Rojas</button><button class="ghost-btn dece-filter-btn" data-filter="Amarilla">Amarillas</button><button class="ghost-btn dece-filter-btn" data-filter="Verde">Verdes</button></div></div><div id="deceAlertList" class="dece-alert-list">${S.alerts.map(alertItem).join('')||'<div class="dece-empty">Sin alertas. El sistema sigue monitoreando.</div>'}</div></section>`;}
function calendar(){return `<section class="dece-grid-2"><article class="dece-panel"><div class="dece-panel-head"><div><h3>Calendario de citas</h3><p>Agenda y confirma acompanamientos.</p></div><button class="primary-btn" id="newAppointmentDemo">Crear cita demo</button></div><div class="dece-appointment-list">${S.appointments.map(appointmentItem).join('')||'<div class="dece-empty">No hay citas solicitadas.</div>'}</div></article><article class="dece-panel"><h3>Agendar manualmente</h3><div class="dece-form"><label class="full">Estudiante<input id="manualStudent" value="estudiante@colegio.edu.ec"></label><label>Fecha<input id="manualDate" type="date" value="${today()}"></label><label>Hora<input id="manualTime" type="time" value="09:00"></label><label class="full">Motivo<textarea id="manualReason">Sesion de acompanamiento emocional</textarea></label><button class="primary-btn full" id="saveManualAppointment">Guardar cita</button></div></article></section>`;}
function followups(){return `<section class="dece-grid-2"><article class="dece-panel"><h3>Ficha de seguimiento</h3><div class="dece-form"><label class="full">Estudiante<input id="followStudent" value="estudiante@colegio.edu.ec"></label><label class="full">Observaciones<textarea id="followObs" placeholder="Observaciones del encuentro..."></textarea></label><label class="full">Acuerdos<textarea id="followAgreements" placeholder="Acuerdos y pasos siguientes..."></textarea></label><label class="full">PDF simulado<input id="followFile" type="file"></label><button class="primary-btn full" id="saveFollowupPro">Guardar seguimiento</button><button class="ghost-btn full" id="exportFollowups">Exportar CSV</button></div><p class="dece-export-note">La subida de PDF es simulada para la demo. No se almacenan archivos sensibles.</p></article><article class="dece-panel"><div class="dece-panel-head"><div><h3>Historial de fichas</h3><p>Seguimientos registrados por el equipo DECE.</p></div></div><div class="dece-follow-list">${S.followups.map(f=>`<article class="dece-follow-card"><h4>${f.student}</h4><p>${f.observations||'Sin observaciones'}</p><p><strong>Acuerdos:</strong> ${f.agreements||'Pendiente'}</p><small>${f.date||''} · ${f.file||'PDF simulado'}</small></article>`).join('')||'<div class="dece-empty">Aun no hay fichas registradas.</div>'}</div></article></section>`;}
function stats(){const c=counts();const rows=[['Participacion estudiantil',Math.min(100,c.moods*12+35)],['Emociones monitoreadas',Math.min(100,c.moods*10+20)],['Uso de Wolf AI',Math.min(100,(S.chat||[]).length*8+25)],['Retos completados',Math.min(100,(S.challenges||[]).length*20)],['Alertas generadas',Math.min(100,S.alerts.length*18)],['Citas gestionadas',Math.min(100,S.appointments.length*24)]];return `<section class="dece-panel"><div class="dece-panel-head"><div><h3>Estadisticas institucionales</h3><p>Indicadores visuales para decisiones del DECE y la institucion.</p></div><button class="ghost-btn" id="exportStats">Exportar resumen</button></div><div class="dece-grid-3">${metric('Participacion',c.moods,'green','Mood Checks')}${metric('Wolf AI',(S.chat||[]).length,'cyan','Mensajes')}${metric('Retos',(S.challenges||[]).length,'yellow','Completados')}</div><div class="dece-bars">${rows.map(r=>`<div class="dece-bar-row"><strong>${r[0]}</strong><div class="dece-bar-track"><span style="width:${r[1]}%"></span></div><span>${r[1]}%</span></div>`).join('')}</div></section>`;}
function body(){const views={'Dashboard DECE':dashboard,'Semáforo Emocional':semaphore,'Mapa de bienestar':wellbeingMap,'Gestión de alertas':alertsView,'Calendario de citas':calendar,'Fichas de seguimiento':followups,'Estadísticas institucionales':stats};return `<div class="dece-pro">${(views[active]||dashboard)()}</div>`;}
function deceUpgrade(){ensureDeceData();e('deceView').innerHTML=shellHeader()+body();bindDece();persist();}
function createFollow(student,obs,agreements){S.followups.unshift({student,date:today(),observations:obs||'Seguimiento generado desde Panel DECE.',agreements:agreements||'Acompanamiento y monitoreo durante la semana.',file:'PDF simulado'});}
function bindDece(){
  document.querySelectorAll('[data-dece-jump]').forEach(b=>b.onclick=()=>{active=b.dataset.deceJump;render();});
  document.querySelectorAll('.dece-attend').forEach(b=>b.onclick=()=>{const a=S.alerts[+b.dataset.i];if(a){a.status='En atencion';notify('Alerta marcada en atencion');persist();render();}});
  document.querySelectorAll('.dece-to-follow').forEach(b=>b.onclick=()=>{const a=S.alerts[+b.dataset.i];if(a){createFollow(a.student,'Ficha creada desde alerta: '+a.reason,'Citar estudiante y registrar acuerdos.');a.status='Ficha creada';notify('Ficha creada desde alerta');persist();render();}});
  document.querySelectorAll('.dece-schedule').forEach(b=>b.onclick=()=>{const a=S.appointments[+b.dataset.i];if(a){a.status='Agendada';notify('Cita agendada');persist();render();}});
  document.querySelectorAll('.dece-complete-appointment').forEach(b=>b.onclick=()=>{const a=S.appointments[+b.dataset.i];if(a){a.status='Realizada';createFollow(a.student,'Cita realizada: '+(a.reason||'Acompanamiento DECE'),'Continuar seguimiento preventivo.');notify('Cita marcada como realizada');persist();render();}});
  document.querySelectorAll('.dece-student-follow').forEach(b=>b.onclick=()=>{active='Fichas de seguimiento';render();setTimeout(()=>{const input=document.getElementById('followStudent');if(input)input.value=b.dataset.email;},40);});
  document.querySelectorAll('.dece-filter-btn').forEach(b=>b.onclick=()=>{const f=b.dataset.filter;const list=document.getElementById('deceAlertList');const data=f==='Todas'?S.alerts:S.alerts.filter(a=>a.level===f);if(list)list.innerHTML=data.map((a,i)=>alertItem(a,S.alerts.indexOf(a))).join('')||'<div class="dece-empty">No hay alertas para este filtro.</div>';bindDece();});
  const manual=document.getElementById('saveManualAppointment');if(manual)manual.onclick=()=>{S.appointments.unshift({student:manualStudent.value,reason:manualReason.value,date:manualDate.value,time:manualTime.value,status:'Agendada',createdAt:new Date().toLocaleString()});notify('Cita guardada');persist();render();};
  const demo=document.getElementById('newAppointmentDemo');if(demo)demo.onclick=()=>{S.appointments.unshift({student:'estudiante@colegio.edu.ec',reason:'Chequeo emocional preventivo',date:today(),time:'11:00',status:'Solicitada',createdAt:new Date().toLocaleString()});notify('Cita demo creada');persist();render();};
  const follow=document.getElementById('saveFollowupPro');if(follow)follow.onclick=()=>{if(!followStudent.value.trim())return notify('Ingresa estudiante');createFollow(followStudent.value,followObs.value,followAgreements.value);notify('Seguimiento guardado');persist();render();};
  const csv=document.getElementById('exportFollowups');if(csv)csv.onclick=()=>exportCsv('seguimientos-wolves.csv',S.followups.map(f=>({estudiante:f.student,fecha:f.date,observaciones:f.observations,acuerdos:f.agreements})));
  const statsBtn=document.getElementById('exportStats');if(statsBtn)statsBtn.onclick=()=>exportCsv('estadisticas-dece-wolves.csv',[counts()]);
  const refresh=document.getElementById('refreshMap');if(refresh)refresh.onclick=()=>notify('Mapa actualizado con datos demo');
}
function exportCsv(filename,rows){const keys=Object.keys(rows[0]||{demo:'sin datos'});const csv=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);notify('CSV exportado');}
window.addEventListener('load',()=>{if(typeof S==='undefined')return;window.dece=dece=deceUpgrade;if(S.role==='dece')render();});
})();